language: c

script: make && make check

matrix:
  include:
   - os: linux
     dist: trusty
     sudo: required
     compiler: gcc
   - os: linux
     dist: trusty
     sudo: required
     compiler: clang
   - os: osx
     osx_image: xcode7.3

