.TH CHARS 1 2016-05-24
.SH NAME
chars - split files into separated characters
.SH SYNOPSIS
.B chars
.RI [ options ]
.RI [ file ]
.SH DESCRIPTION
Split files into characters, one per line or separated by spaces
with additional formatting and escaping options.

The \fIfiles\fP parameter, if set, is used as the input file.
If unset, or when the value is \fB-\fP, standard input is used.
By default, characters are printed one per line and
non-printable characters are escaped.
.SH OPTIONS
.SS General options
.TP
.BR -v ", " --version
Print version number and exit.
.TP
.BR -h ", " --help
Print a help message and exit.
.TP
.BI -o " FILE, " --output " FILE"
File to write the output to.
Use a hyphen (\fB-\fP) to write to standard output, which is the default.
.TP
.BI -p ", " --printable
Skip control characters in the input.
.BI --oneline
Output characters one one line, separated by spaces.

When combined with \fB--raw\fP
and none of the output format options (\fB-uxX\fP)
or \fB--quote\fP,
newline characters will be output as-is, creating line. breaks.
.TP
.BR -r ", " --raw
Do not escape non-printable characters.

When combined with \fB--oneline\fP
and none of the output format options (\fB-uxX\fP)
or \fB--quote\fP,
newline characters will be output as-is, creating line. breaks.
.TP
.BI -q ", " --[no-]quote
Quote characters with a double qoute character: ". Disabled by default.
.SS Output style options
.TP
.BI -c ", " --chars
Output the ASCII characters. This is the default. Equivalent to the
\fIprintf(2)\fP format string \fB%c\fP.
.TP
.BI -u ", " --decimal
Output decimal ASCII codepoints. Equivalent to the \fIprintf(2)\fP format
string \fB%3i\fP.
.TP
.BI -x ", " --hex
Output lower case hexadecimal ASCII codepoints. Equivalent to the
\fIprintf(2)\fP format string \fB%02x\fP.
.TP
.BI -X ", " --Hex
Output upper case hexadecimal ASCII codepoints. Equivalent to the
\fIprintf(2)\fP format string \fB%02X\fP.
.SH AUTHOR
Written by Iku <iku@yokatana.com>, 2016.
